export const cities = [
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Andorra la Vella", country: "Andorra" },
  { name: "Athens", country: "Greece" },
  { name: "Belgrade", country: "Serbia" },
  { name: "Berlin", country: "Germany" },
  { name: "Bern", country: "Switzerland" },
  { name: "Bratislava", country: "Slovakia" },
  { name: "Brussels", country: "Belgium" },
  { name: "Bucharest", country: "Romania" },
  { name: "Budapest", country: "Hungary" },
  { name: "Chisinau", country: "Moldova" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Dublin", country: "Ireland" },
  { name: "Helsinki", country: "Finland" },
  { name: "Kyiv", country: "Ukraine" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Ljubljana", country: "Slovenia" },
  { name: "London", country: "United Kingdom" },
  { name: "Luxembourg", country: "Luxembourg" },
  { name: "Madrid", country: "Spain" },
  { name: "Minsk", country: "Belarus" },
  { name: "Monaco", country: "Monaco" },
  { name: "Moscow", country: "Russia" },
  { name: "Nicosia", country: "Cyprus" },
  { name: "Oslo", country: "Norway" },
  { name: "Paris", country: "France" },
  { name: "Podgorica", country: "Montenegro" },
  { name: "Prague", country: "Czech Republic" },
  { name: "Pristina", country: "Kosovo" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "Riga", country: "Latvia" },
  { name: "Rome", country: "Italy" },
  { name: "San Marino", country: "San Marino" },
  { name: "Sarajevo", country: "Bosnia and Herzegovina" },
  { name: "Skopje", country: "North Macedonia" },
  { name: "Sofia", country: "Bulgaria" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Tallinn", country: "Estonia" },
  { name: "Tirana", country: "Albania" },
  { name: "Vaduz", country: "Liechtenstein" },
  { name: "Valletta", country: "Malta" },
  { name: "Vatican City", country: "Vatican City" },
  { name: "Vienna", country: "Austria" },
  { name: "Vilnius", country: "Lithuania" },
  { name: "Warsaw", country: "Poland" },
  { name: "Zagreb", country: "Croatia" },
];

export default cities;